/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DefaultButton {
        "buttonBg": 'primary' | 'secondary';
        "buttonIcon": string;
        "buttonType": 'rounded' | 'square';
        "iconPosition": 'left' | 'right';
    }
    interface WjButton {
        "bg": 'primary' | 'secondary' | 'negative';
        "border": 'rounded' | 'square';
        "buttonIcon": string;
        "iconPosition": 'left' | 'right';
    }
}
declare global {
    interface HTMLDefaultButtonElement extends Components.DefaultButton, HTMLStencilElement {
    }
    var HTMLDefaultButtonElement: {
        prototype: HTMLDefaultButtonElement;
        new (): HTMLDefaultButtonElement;
    };
    interface HTMLWjButtonElement extends Components.WjButton, HTMLStencilElement {
    }
    var HTMLWjButtonElement: {
        prototype: HTMLWjButtonElement;
        new (): HTMLWjButtonElement;
    };
    interface HTMLElementTagNameMap {
        "default-button": HTMLDefaultButtonElement;
        "wj-button": HTMLWjButtonElement;
    }
}
declare namespace LocalJSX {
    interface DefaultButton {
        "buttonBg"?: 'primary' | 'secondary';
        "buttonIcon"?: string;
        "buttonType"?: 'rounded' | 'square';
        "iconPosition"?: 'left' | 'right';
    }
    interface WjButton {
        "bg"?: 'primary' | 'secondary' | 'negative';
        "border"?: 'rounded' | 'square';
        "buttonIcon"?: string;
        "iconPosition"?: 'left' | 'right';
    }
    interface IntrinsicElements {
        "default-button": DefaultButton;
        "wj-button": WjButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "default-button": LocalJSX.DefaultButton & JSXBase.HTMLAttributes<HTMLDefaultButtonElement>;
            "wj-button": LocalJSX.WjButton & JSXBase.HTMLAttributes<HTMLWjButtonElement>;
        }
    }
}
